version: '3'
services:
  mysql:
    image: mariadb:10.4.7
    env_file: .env
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - 13306:3306
    command: |
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  login-api:
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/foody/run.sh
      - ./foody-login-api/build/libs:/home/foody/libs
    ports:
      - 8001:8080
    depends_on:
      - mysql
    command: bash -c "cd /home/foody && sh run.sh"
  admin-api:
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/foody/run.sh
      - ./foody-admin-api/build/libs:/home/foody/libs
    ports:
      - 8002:8080
    depends_on:
      - mysql
    command: bash -c "cd /home/foody && sh run.sh"
  customer-api:
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/foody/run.sh
      - ./foody-customer-api/build/libs:/home/foody/libs
    ports:
      - 8003:8080
    depends_on:
      - mysql
    command: bash -c "cd /home/foody && sh run.sh"
  restaurant-api:
    image: openjdk:8
    env_file: .env
    volumes:
      - ./run.sh:/home/foody/run.sh
      - ./foody-restaurant-api/build/libs:/home/foody/libs
    ports:
      - 8004:8080
    depends_on:
      - mysql
    command: bash -c "cd /home/foody && sh run.sh"
  admin-web:
    image: node:10.16.3
    volumes:
      - ./foody-admin-web:/home/foody
    ports:
      - 8082:3000
    environment:
      - VUE_APP_API_BASE_URL=http://localhost:8002
      - VUE_APP_LOGIN_API_BASE_URL=http://localhost:8001
    command: bash -c "cd /home/foody && npm run serve"
    healthcheck:
      test: curl -sS http://localhost:8080 || exit 1
      timeout: 10s
      retries: 10
  customer-web:
    image: node:10.16.3
    volumes:
      - ./foody-customer-web:/home/foody
    ports:
      - 8083:3000
    environment:
      - VUE_APP_API_BASE_URL=http://localhost:8003
      - VUE_APP_LOGIN_API_BASE_URL=http://localhost:8001
    command: bash -c "cd /home/foody && npm run serve"
    healthcheck:
      test: curl -sS http://localhost:8080 || exit 1
      timeout: 10s
      retries: 10
  restaurant-web:
    image: node:10.16.3
    volumes:
      - ./foody-restaurant-web:/home/foody
    ports:
      - 8084:3000
    environment:
      - VUE_APP_API_BASE_URL=http://localhost:8004
      - VUE_APP_LOGIN_API_BASE_URL=http://localhost:8001
    command: bash -c "cd /home/foody && npm run serve"
    healthcheck:
      test: curl -sS http://localhost:8080 || exit 1
      timeout: 10s
      retries: 10